services:
  homeassistant:
    container_name: homeassistant
    image: ghcr.io/home-assistant/home-assistant:stable
    volumes:
      - ./config:/config
      - ./baiwei-iot/custom_components:/config/custom_components
    environment:
      - TZ=Asia/Shanghai
    restart: unless-stopped
    network_mode: host
